FROM volkant/dropbox-api-extended:latest

VOLUME /tmp
ADD content/config config
ADD content/config/application.properties config/application.properties
ADD content/config/logback.xml config/logback.xml

EXPOSE 8081